
[[collection]]
type = "art"
title = "Title"
# subtitle = "Subtitle" # optional
link = "https://example.com" # optional
img = "https://example.com/image.png"
# content = "Content" # optional
# footer = "Footer" # optional

[[collection]]
type = "art"
title = "Title"
# subtitle = "Subtitle" # optional
link = "https://example.com" # optional
img = "https://example.com/image.png"
# content = "Content" # optional
# footer = "Footer" # optional

[[collection]]
type = "art"
title = "Title"
# subtitle = "Subtitle" # optional
link = "https://example.com" # optional
img = "https://example.com/image.png"
# content = "Content" # optional
# footer = "Footer" # optional

[[collection]]
type = "art"
title = "Title"
# subtitle = "Subtitle" # optional
link = "https://example.com" # optional
img = "https://example.com/image.png"
# content = "Content" # optional
# footer = "Footer" # optional

[[collection]]
type = "art"
title = "Title"
# subtitle = "Subtitle" # optional
link = "https://example.com" # optional
img = "https://example.com/image.png"
# content = "Content" # optional
# footer = "Footer" # optional